name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: docker pull bilalms/ecom-go:latest

    - name: Delete old Docker container
      run: sudo docker rm -f ecom-go-container || true

    - name: Run Docker container
      run: sudo docker run -d -p 8080:8080 --name ecom-go-container bilalms/ecom-go:latest
