name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login DockerHub
      env:
        DOCKER_USER_NAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
    - name: Build the Docker image
      run: docker build -t ecom-go .

    - name: Push to Dockerhub
      run: docker push muhammedbilals/ecom-go:latest
